version: '3'
services:
  redmine:
    image: redmine:3.3.1
    restart: always
    ports:
      - 3001:3000
    env_file:
      - .env
    volumes:
      - ./data/redmine_data/config:/usr/src/redmine/config
      - ./data/redmine-plugins:/usr/src/redmine/plugins

  mysql_redmine:
    image: mysql:5.7
    restart: always
    command: mysqld --max_allowed_packet=256M
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=redmine
    volumes:
      - ./data/mysql-data_red:/var/lib/mysql 

#docker cp  95e84b63c2d4:/usr/src/redmine/config data/redmine_data/config/